name: CD Dreamliner

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend-dreamliner/**'
            frontend:
              - 'frontend-dreamliner/**'

  push-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login ke GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend-dreamliner
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dreamliner-backend:latest
            ghcr.io/${{ github.repository_owner }}/dreamliner-backend:${{ github.sha }}

  push-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login ke GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-dreamliner
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dreamliner-frontend:latest
            ghcr.io/${{ github.repository_owner }}/dreamliner-frontend:${{ github.sha }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL_PROD }}

  deploy-backend:
    needs: push-backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend ke EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dreamliner/backend-dreamliner
            docker compose pull
            docker compose up -d

  deploy-frontend:
    needs: push-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend ke EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/dreamliner/frontend-dreamliner
            docker compose pull
            docker compose up -d
