services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - dreamliner-network
    restart: on-failure

  worker:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    entrypoint: ["node"]
    command: ["rabbitMQ/start/startLightWorker.js"]
    volumes:
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - dreamliner-network
    restart: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - dreamliner-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dreamliner-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - dreamliner-network

volumes:
  dreamliner-db-data:

networks:
  dreamliner-network:
